name: Pull Request
on:
  pull_request:
    types: [ opened, edited, reopened ]
    branches:
      - master

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Lint
        run: npm run test:lint